apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlp-ingress
spec:
  rules:
  - host: nlp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nlp-inference
            port:
              number: 80